name = "Econometrics"
uuid = "4d6a76a9-bfbc-5492-8924-cf6ed7875f06"
license = "ISC"
description = "Econometrics in Julia"
maintainer = "José Bayoán Santiago Calderón"
version = "0.2.7"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"

[compat]
CategoricalArrays = "0.8"
Distributions = "0.23"
FillArrays = "0.9"
ForwardDiff = "0.10"
Optim = "1"
Parameters = "0.12"
StatsBase = "0.33"
StatsFuns = "0.9"
StatsModels = "0.6"
TableOperations = "0.2"
julia = "1"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "RDatasets", "Test"]
